export const GYM = {
  MAX_RANGE_IN_KILOMETERS: 10,
}

export const CHECK_IN = {
  MAX_DISTANCE_IN_KILOMETERS: 0.1,
  MAX_TIME_TO_VALIDATE_IN_MINUTES: 20,
}

export const PAGINATION = {
  MAX_ITEMS_PER_PAGE: 20,
}
