name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: ignite-gym-pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.3.1

      - name: Cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node and install project dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
          check-latest: true
          cache: 'pnpm'

        if: steps.pnpm-cache.outputs.cache-hit != 'true'
      - run: pnpm install --prefer-offline

      - run: pnpm run test:e2e
        env:
          PORT: 3333
          HASH_ROUNDS: 4
          JWT_SECRET: supersecret
          JWT_EXPIRES_IN: 1d
          JWT_REFRESH_EXPIRES_IN: 30d
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/ignite-gym-pass?schema=public"
